# Generated by Django 2.2.7 on 2020-03-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createclasstime',
            name='time',
        ),
    ]
