# Generated by Django 2.2.7 on 2020-04-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentface', '0005_user_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='classtime',
            field=models.DateTimeField(null=True),
        ),
    ]
