# Generated by Django 2.2.7 on 2020-04-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentface', '0006_auto_20200402_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default='file/S.png', upload_to='file/'),
        ),
    ]
