# Generated by Django 2.2.7 on 2020-04-15 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentface', '0007_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='actualclasstime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentface.createclasstime'),
        ),
    ]
