# Generated by Django 2.2.7 on 2020-04-20 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentface', '0008_attendance_actualclasstime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='c_name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='s_name',
        ),
    ]
